// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdcksfagqqluojpfxpqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kY2tzZmFncXFsdW9qcGZ4cHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTQyODMsImV4cCI6MjA2ODMzMDI4M30.fNEqCmHLDKtXcuU4Of6IkPZyRHq4ZJj7bLlA89m6TJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});